### ISSUE TITLE
beaker unable to execute vagrant when using zsh (pathing issue)

### ISSUE THREAD

**Issue by petems** [puppetlabs/beaker#612]
So I kept meaning to open an issue for this, but I thought it was only happening to me because I had a weird boxen setup, but I've seen it happen to two other people @terrimonster and @zacharyalexstern who didn't have boxen (but did have rbenv, which I assume is the issue)

So heres a summary:

Have rbenv installed. Have Vagrant installed.

Clone a repo that has some beaker rspec tests:

```
git clone https://github.com/puppetlabs/puppetlabs-apt
```

Try to run a beaker test that uses the vagrant hypervisor:

```
bundle exec rspec spec/acceptance/apt_spec.rb
```

You get the following error message:

```
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:166:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant up' (RuntimeError)
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/open3.rb:99:in `popen3'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:161:in `block in vagrant_cmd'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `chdir'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `vagrant_cmd'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:121:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:68:in `create'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:48:in `block in provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `each_key'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:29:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:40:in `block in <top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core.rb:154:in `configure'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
	from /Users/petersouter/projects/puppetlabs-apt/spec/spec_helper_acceptance.rb:1:in `require'
	from /Users/petersouter/projects/puppetlabs-apt/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
	from /Users/petersouter/projects/puppetlabs-apt/spec/acceptance/apt_spec.rb:1:in `require'
	from /Users/petersouter/projects/puppetlabs-apt/spec/acceptance/apt_spec.rb:1:in `<top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

I believe this is because of the vagrant shim:

```
$ which vagrant
/opt/boxen/rbenv/shims/vagrant
```

Delete the shim:

```
$ rm -rf /opt/boxen/rbenv/shims/vagrant
$ which vagrant
/usr/bin/vagrant
```

Then you get a slightly different error:

```
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:166:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant destroy --force' (RuntimeError)
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
	from /opt/rubies/2.0.0-p451/lib/ruby/2.0.0/open3.rb:99:in `popen3'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:161:in `block in vagrant_cmd'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `chdir'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:159:in `vagrant_cmd'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor/vagrant.rb:117:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/hypervisor.rb:68:in `create'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:48:in `block in provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `each_key'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-2.1.0/lib/beaker/network_manager.rb:47:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/beaker_shim.rb:29:in `provision'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:40:in `block in <top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core.rb:154:in `configure'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `require'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/beaker-rspec-4.0.0/lib/beaker-rspec.rb:1:in `<top (required)>'
	from /Users/petersouter/projects/puppetlabs-apt/spec/spec_helper_acceptance.rb:1:in `require'
	from /Users/petersouter/projects/puppetlabs-apt/spec/spec_helper_acceptance.rb:1:in `<top (required)>'
	from /Users/petersouter/projects/puppetlabs-apt/spec/acceptance/apt_spec.rb:1:in `require'
	from /Users/petersouter/projects/puppetlabs-apt/spec/acceptance/apt_spec.rb:1:in `<top (required)>'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `block in load_spec_files'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `each'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/configuration.rb:1065:in `load_spec_files'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:18:in `run'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
	from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'
```

Then add `vagrant-wrapper` gem to the Gemfile:

```
gem 'vagrant-wrapper', :require => false
```

Then everything works normally:

```
Beaker::Hypervisor, found some vagrant boxes to create
==> ubuntu-server-12042-x64: VM not created. Moving on...
Bringing machine 'ubuntu-server-12042-x64' up with 'virtualbox' provider...
==> ubuntu-server-12042-x64: Importing base box 'ubuntu-server-12042-x64-vbox4210-nocm'...
==> ubuntu-server-12042-x64: Matching MAC address for NAT networking...
```

I'm not super certain whats happening, I'm assuming it's a pathing issue somewhere. The shim seems to be the key thing I think.

https://github.com/sstephenson/rbenv/issues/388 and http://stackoverflow.com/questions/16496333/rbenv-continually-generating-vagrant-shim might help:

The SO question suggests
```
alias vagrant /usr/bin/vagrant
```

But I'd prefer not to have to change my dotfiles...

**Comment by zacharyalexstern** [comment]
For what it's worth, this doesn't *always* happen to me, so it may depend on the version of beaker. E.g. I don't have this problem with a brand new module generated via `garethr/puppet-module-skeleton` but I do have the problem trying to run the acceptance tests for `puppetlabs/inifile`.

**Comment by petems** [comment]
Ok, so this is happening with beaker master for me:

```
gem "beaker", :git => 'https://github.com/puppetlabs/beaker.git', :ref => '6776472eca29ee9526b3979362ea9690c0ca7261'
```

**Comment by petems** [comment]
@zacharyalexstern can you paste the version of beaker from the Gemfile.lock you've got in that new module generated?

**Comment by zacharyalexstern** [comment]
```
LOLcalhost :: src/Puppet/puppetlabs-pse ‹set_ntp_server› % cat Gemfile.lock|grep beaker
  remote: https://github.com/nrvale0/beaker.git
    beaker (2.1.0)
    beaker-rspec (4.0.0)
      beaker (~> 2.0)
```

**Comment by anodelman** [comment]
I'm going to file an internal bug for tracking this as well.

**Comment by petems** [comment]
Now that https://github.com/puppetlabs/beaker/pull/610/ has been merged, it gives the probable reason behind the failure:

```
Hypervisor for ubuntu-server-12042-x64 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/bundler/gems/beaker-7c88b74abbf1/lib/beaker/hypervisor/vagrant.rb:166:in `block (2 levels) in vagrant_cmd': Failed to exec 'vagrant destroy --force'. Error was /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/bundler-1.7.9/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': vagrant-wrapper is not part of the bundle. Add it to Gemfile. (Gem::LoadError) (RuntimeError)
```

**Comment by petems** [comment]
I've found this doesn't happen with a vanilla bash shell, only zsh...

**Comment by petems** [comment]
Yep, I'm on a new machine without oh-my-zsh, using bash dotfiles and this works fine without having to delete the vagrant shim or install vagrant-wrapper, I think this is probably a pathing issue.

**Comment by anodelman** [comment]
@kevpl can you take a look at this?  I don't run zsh...

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-19
