### ISSUE TITLE
Masterless Beaker Parallel tests

### ISSUE THREAD

**Issue by qbraksa** [puppetlabs/beaker#623]
Hi, 

Maybe it's just me, but I keep getting this : 

```
Failures:

  1) jenkins default parameters should work with no errors based on the example
     Failure/Error: Unable to find matching line from backtrace
     Beaker::DSL::Outcomes::FailTest:
        There should be one host with default defined!
    # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/beaker-1.20.1/lib/beaker/dsl/roles.rb:157:in `rescue in find_only_one'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/beaker-1.20.1/lib/beaker/dsl/roles.rb:155:in `find_only_one'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/beaker-1.20.1/lib/beaker/dsl/roles.rb:88:in `default'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/beaker-rspec-3.0.0/lib/beaker-rspec/helpers/serverspec.rb:40:in `ssh_exec!'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/beaker-rspec-3.0.0/lib/beaker-rspec/helpers/serverspec.rb:22:in `run_command'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/gems/specinfra-1.27.5/lib/specinfra/backend/exec.rb:184:in `check_os'

  ... 
```

Here's my `default.yml` : 

```
HOSTS:

  ubuntu-server-12042-x64:
     roles:
       - agent
     platform: ubuntu-server-12.04-64bits
     box : ubuntu/precise64
     hypervisor : vagrant

  ubuntu-server-1404-x64:
     roles:
       - agent
     platform: ubuntu-server-14.04-amd64
     box: ubuntu/trusty64
     hypervisor : vagrant

CONFIG:
  log_level: debug
  type: foss
```

Thanks in advance guys!

**Comment by anodelman** [comment]
Beaker can't determine a default host - which would be the host that has the 'master' role or the only host in a single host configuration file.

**Comment by qbraksa** [comment]
How about if I want to run Beaker masterless but still have multiple hosts config file ?

**Comment by anodelman** [comment]
Masterless installs will be supported with https://github.com/puppetlabs/beaker/pull/597.  Not yet merged, but soon.

**Comment by qbraksa** [comment]
Oh Alright! Thanks for the quick response! I'll keep an eye on #597 then!

**Comment by qbraksa** [comment]
Hi (again) 

I see that #597 was merged (thanks a lot by the way), which is what i'm using now! So thanks again!

But weirdly I'm still getting `There should be one host with default defined!`

And here's the exact error i'm getting : 

```
Failures:

  1) test default parameters Should work
     Failure/Error: shell "echo 'hello'"
     Beaker::DSL::Outcomes::FailTest:
       There should be one host with default defined!

     # /home/zakaria/.rvm/gems/ruby-2.1.3/bundler/gems/beaker-7c88b74abbf1/lib/beaker/dsl/roles.rb:175:in `rescue in find_only_one'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/bundler/gems/beaker-7c88b74abbf1/lib/beaker/dsl/roles.rb:173:in `find_only_one'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/bundler/gems/beaker-7c88b74abbf1/lib/beaker/dsl/roles.rb:164:in `find_host_with_role'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/bundler/gems/beaker-7c88b74abbf1/lib/beaker/dsl/roles.rb:90:in `default'
     # /home/zakaria/.rvm/gems/ruby-2.1.3/bundler/gems/beaker-7c88b74abbf1/lib/beaker/dsl/helpers.rb:132:in `shell'
     # ./spec/acceptance/test_spec.rb:8:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 27.8 seconds (files took 3 minutes 49.8 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/acceptance/test_spec.rb:7 # test default parameters Should work
```

Here's also my Gemfile 

```
source 'https://rubygems.org'
gem 'rspec'
gem 'beaker', git: 'https://github.com/puppetlabs/beaker.git'
gem 'beaker-rspec'
gem 'serverspec'
```

**Comment by anodelman** [comment]
Add 'masterless' to the config section:

CONFIG:
  log_level: debug
  type: foss
  masterless: true

**Comment by anodelman** [comment]
Any help from the last comment?

**Comment by anodelman** [comment]
This looks like masterless interacting with beaker-rspec incorrectly.  We'll investigate further.

**Comment by anodelman** [comment]
Sorry, this was overlooked.  Will get it back on our TODO list.

**Comment by anodelman** [comment]
This is still going through internal testing.  We haven't forgotten you!

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-20
