### ISSUE TITLE
Beaker running under rake doesn't trap interrupt signals

### ISSUE THREAD

**Issue by madAndroid** [puppetlabs/beaker#637]
When running via the cli, there does appear to be code which traps interrupt signals, but when running under rake/rspec, any use of interrupt doesn't stop execution: the beaker run continues to happen in the background, causing undesirable results.

I'm not sure if this is the expected behaviour, but it appears to interfere with the workflow. I'm also uncertain whether this is a symptom only affecting my environment, or whether this is a known issue.

For example:  (apologies for the length of the example):
```
bash-3.2$  bundle exec rake acceptance
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -S rspec spec/acceptance
Hypervisor for vagrant-centos7 is vagrant
Beaker::Hypervisor, found some vagrant boxes to create
==> vagrant-centos7: VM not created. Moving on...
created Vagrantfile for VagrantHost vagrant-centos7
Bringing machine 'vagrant-centos7' up with 'virtualbox' provider...
==> vagrant-centos7: Importing base box 'puppetlabs/centos-7.0-64-nocm'...
==> vagrant-centos7: Matching MAC address for NAT networking...
==> vagrant-centos7: Checking if box 'puppetlabs/centos-7.0-64-nocm' is up to date...
==> vagrant-centos7: There was a problem while downloading the metadata for your box
==> vagrant-centos7: to check for updates. This is not an error, since it is usually due
==> vagrant-centos7: to temporary network problems. This is just a warning. The problem
==> vagrant-centos7: encountered was:
==> vagrant-centos7:
==> vagrant-centos7: SSL certificate problem: unable to get local issuer certificate
==> vagrant-centos7: More details here: http://curl.haxx.se/docs/sslcerts.html
==> vagrant-centos7:
==> vagrant-centos7: curl performs SSL certificate verification by default, using a "bundle"
==> vagrant-centos7:  of Certificate Authority (CA) public keys (CA certs). If the default
==> vagrant-centos7:  bundle file isn't adequate, you can specify an alternate file
==> vagrant-centos7:  using the --cacert option.
==> vagrant-centos7: If this HTTPS server uses a certificate signed by a CA represented in
==> vagrant-centos7:  the bundle, the certificate verification probably failed due to a
==> vagrant-centos7:  problem with the certificate (it might be expired, or the name might
==> vagrant-centos7:  not match the domain name in the URL).
==> vagrant-centos7: If you'd like to turn off curl's verification of the certificate, use
==> vagrant-centos7:  the -k (or --insecure) option.
==> vagrant-centos7:
==> vagrant-centos7: If you want to check for box updates, verify your network connection
==> vagrant-centos7: is valid and try again.
==> vagrant-centos7: Setting the name of the VM: vagrant-centos7yml_vagrant-centos7_1421831191816_44133
==> vagrant-centos7: Clearing any previously set network interfaces...
==> vagrant-centos7: Preparing network interfaces based on configuration...
    vagrant-centos7: Adapter 1: nat
    vagrant-centos7: Adapter 2: hostonly
==> vagrant-centos7: Forwarding ports...
    vagrant-centos7: 22 => 2222 (adapter 1)
==> vagrant-centos7: Running 'pre-boot' VM customizations...
==> vagrant-centos7: Booting VM...
==> vagrant-centos7: Waiting for machine to boot. This may take a few minutes...
    vagrant-centos7: SSH address: 127.0.0.1:2222
    vagrant-centos7: SSH username: vagrant
    vagrant-centos7: SSH auth method: private key
    vagrant-centos7: Warning: Connection timeout. Retrying...
    vagrant-centos7:
    vagrant-centos7: Vagrant insecure key detected. Vagrant will automatically replace
    vagrant-centos7: this with a newly generated keypair for better security.
    vagrant-centos7:
    vagrant-centos7: Inserting generated public key within guest...
    vagrant-centos7: Removing insecure key from the guest if its present...
    vagrant-centos7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> vagrant-centos7: Machine booted and ready!
==> vagrant-centos7: Checking for guest additions in VM...
==> vagrant-centos7: Setting hostname...
==> vagrant-centos7: Configuring and enabling network interfaces...
==> vagrant-centos7: Mounting shared folders...
    vagrant-centos7: /vagrant => /srv/data/repos/ITV/puppet/puppet-module-itv_base_service_profile/.vagrant/beaker_vagrant_files/vagrant-centos7.yml
configure vagrant boxes (set ssh-config, switch to root user, hack etc/hosts)
Give root a copy of current user's keys, on vagrant-centos7

vagrant-centos7 11:06:56$ sudo su -c "cp -r .ssh /root/."
Created ssh connection to 10.255.249.180, user: vagrant, opts: {:config=>"/var/folders/4t/q75s_5rn0854z9qncbbydb2c0000gn/T/vagrant-centos720150121-38150-fe1f09", :user=>"vagrant"}
Allocated a PTY on 10.255.249.180 for "sudo su -c \"cp -r .ssh /root/.\""

vagrant-centos7 executed in 0.06 seconds
Update /etc/ssh/sshd_config to allow root login

vagrant-centos7 11:06:56$ sudo su -c "sed -ri 's/^#?PermitRootLogin no|^#?PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config"
Allocated a PTY on 10.255.249.180 for "sudo su -c \"sed -ri 's/^#?PermitRootLogin no|^#?PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config\""

vagrant-centos7 executed in 0.02 seconds

vagrant-centos7 11:06:56$ sudo -E /sbin/service sshd restart
Redirecting to /bin/systemctl restart  sshd.service

vagrant-centos7 executed in 0.04 seconds

vagrant-centos7 11:06:57$ echo '127.0.0.1       localhost localhost.localdomain
10.255.249.180  vagrant-centos7
' > /etc/hosts
Created ssh connection to 10.255.249.180, user: root, opts: {:config=>"/var/folders/4t/q75s_5rn0854z9qncbbydb2c0000gn/T/vagrant-centos720150121-38150-nwi3ae", :user=>"root"}

vagrant-centos7 executed in 0.04 seconds

vagrant-centos7 11:06:57$ rpm -q curl
curl-7.29.0-19.el7.x86_64

vagrant-centos7 executed in 0.03 seconds

vagrant-centos7 11:06:57$ rpm -q ntpdate
package ntpdate is not installed

vagrant-centos7 executed in 0.01 seconds
Exited: 1

vagrant-centos7 11:06:58$ yum -y  install ntpdate
Loaded plugins: fastestmirror
^C
Exiting... Interrupt again to exit immediately.
rake aborted!
Interrupt:
/Library/Ruby/Gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:169:in `system'
/Library/Ruby/Gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:169:in `run_task'
/Library/Ruby/Gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:148:in `block (2 levels) in initialize'
/Library/Ruby/Gems/2.0.0/gems/rspec-core-2.99.2/lib/rspec/core/rake_task.rb:146:in `block in initialize'
Tasks: TOP => acceptance
(See full trace by running task with --trace)

bash-3.2$ 
bash-3.2$
bash-3.2$ 

Determining fastest mirrors
 * base: ftp.is.co.za
 * extras: ftp.is.co.za
 * updates: ftp.is.co.za
bash-3.2$ 
Resolving Dependencies
--> Running transaction check
---> Package ntpdate.x86_64 0:4.2.6p5-19.el7.centos will be installed
--> Finished Dependency Resolution
bash-3.2$ 
warning: /var/cache/yum/x86_64/7/updates/packages/ntpdate-4.2.6p5-19.el7.centos.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-0.1406.el7.centos.2.3.x86_64 (@anaconda)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : ntpdate-4.2.6p5-19.el7.centos.x86_64                         1/1
  Verifying  : ntpdate-4.2.6p5-19.el7.centos.x86_64                         1/1

bash-3.2$ 
bash-3.2$
bash-3.2$ 
Installed:
  ntpdate.x86_64 0:4.2.6p5-19.el7.centos

Complete!

vagrant-centos7 executed in 50.99 seconds

vagrant-centos7 11:22:21$ echo "/usr/bin"
/usr/bin
bash-3.2$ 
```

What this shows is that after hitting ctrl-c once the beaker run has begun, rake receives the interrupt, but the underlying beaker code doesn't, and as a result, the run is forced into the background, and the output surfaces during the current shell session. The additional `bash-3.2$` output above is when hitting enter in my terminal after pressing ctrl-c :)

When adding this patch:
```
diff --git a/lib/beaker.rb b/lib/beaker.rb
index 118a8a7..e6f4be3 100644
--- a/lib/beaker.rb
+++ b/lib/beaker.rb
@@ -1,4 +1,7 @@
 require 'rubygems' unless defined?(Gem)
+
+Signal.trap("INT") { exit 1 }
+
 module Beaker

```
The interrupt is correctly handled, and the beaker run is terminated upon ctrl-c, as it should be.
However, I'm not entirely sure this is the best location for the interrupt handling to be placed, perhaps it should be added to one of the other classes?

#### To reproduce:
- Add a nodeset which uses a vagrant box
- Wait until the box is up, and provisioning starts
- Hit ctrl-c
- Watch output resurface when attempting to use shell for other purposes

#### Environment:
- Beaker:
```
bash-3.2$ bundle list | grep beaker
  * beaker (2.1.0 74e7ffb)
  * beaker-rspec (4.0.0)
```
- OSX 10.10.1 (with ruby: `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`)
- Vagrant 1.7.2

**Comment by anodelman** [comment]
This is worth looking at, but I'm also unsure what the correct solution is here.

We are merging beaker and beaker-rspec in the near term and that may provide a better path to success.

**Comment by madAndroid** [comment]
Okay, awesome -  thanks for the update :-)

**Comment by anodelman** [comment]
Let me file something internally to track this.

**Comment by anodelman** [comment]
Follow up here:

https://tickets.puppetlabs.com/browse/BKR-23
