### ISSUE TITLE
`log_level: debug` crashes Beaker

### ISSUE THREAD

**Issue by cassianoleal** [puppetlabs/beaker#653]
When I enable `log_level: debug` on my nodeset, I get this crash:

```
-bash-4.1$ bundle exec rspec spec/acceptance/
/opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
/opt/go/agent0/.gems/ruby/2.1.0/gems/specinfra-2.12.1/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Hypervisor for centos6 is docker
Beaker::Hypervisor, found some docker boxes to create
Provisioning docker
provisioning centos6
Creating image
Dockerfile is         FROM chef/centos-6
          RUN yum clean all
          RUN yum install -y sudo openssh-server openssh-clients curl ntpdate
          RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key
          RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key
        RUN mkdir -p /var/run/sshd
        RUN echo root:root | chpasswd
RUN mkdir -p /root/.ssh
RUN yum -y install tar
        EXPOSE 22
        CMD ["/sbin/init"]
/opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:173:in `convert': undefined method `force_encoding' for :post:Symbol (NoMethodError)
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:169:in `block in convert'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:168:in `map'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:168:in `convert'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:272:in `block in optionally_color'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:270:in `each'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:270:in `optionally_color'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/logger.rb:212:in `debug'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/docker-api-1.17.0/lib/docker/connection.rb:40:in `request'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/docker-api-1.17.0/lib/docker/connection.rb:59:in `block (2 levels) in <class:Connection>'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/docker-api-1.17.0/lib/docker/image.rb:199:in `build'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/hypervisor/docker.rb:26:in `block in provision'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/hypervisor/docker.rb:22:in `each'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/hypervisor/docker.rb:22:in `provision'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/hypervisor.rb:68:in `create'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:48:in `block in provision'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:47:in `each_key'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-2.0.0/lib/beaker/network_manager.rb:47:in `provision'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec/beaker_shim.rb:29:in `provision'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec/spec_helper.rb:42:in `block in <top (required)>'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core.rb:81:in `configure'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec/spec_helper.rb:5:in `<top (required)>'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec.rb:5:in `require'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec.rb:5:in `<module:BeakerRSpec>'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/beaker-rspec-5.0.1/lib/beaker-rspec.rb:1:in `<top (required)>'
	from /opt/go/agent0/.gems/ruby/2.1.0/bundler/gems/gamesys_puppet_spec_helper-56066fb0e638/lib/gamesys_puppet_spec_helper/spec_helper_acceptance.rb:1:in `require'
	from /opt/go/agent0/.gems/ruby/2.1.0/bundler/gems/gamesys_puppet_spec_helper-56066fb0e638/lib/gamesys_puppet_spec_helper/spec_helper_acceptance.rb:1:in `<top (required)>'
	from /opt/go/agent0/go-agent/pipelines/remote_file/remote_file/spec/spec_helper_acceptance.rb:2:in `require'
	from /opt/go/agent0/go-agent/pipelines/remote_file/remote_file/spec/spec_helper_acceptance.rb:2:in `<top (required)>'
	from /opt/go/agent0/go-agent/pipelines/remote_file/remote_file/spec/acceptance/init_spec.rb:1:in `require'
	from /opt/go/agent0/go-agent/pipelines/remote_file/remote_file/spec/acceptance/init_spec.rb:1:in `<top (required)>'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /opt/go/agent0/.gems/ruby/2.1.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /opt/go/agent0/.gems/ruby/2.1.0/bin/rspec:23:in `load'
	from /opt/go/agent0/.gems/ruby/2.1.0/bin/rspec:23:in `<main>'
```

I traced down to a symbol (`:put` IIRC) being passed to the line where it crashes. If I replace `string` with `string.to_s` on lines `173` and `174`, it works. I can send a PR but I'm not sure that's the best way to fix it.

**Comment by electrical** [comment]
Hi,

Please use beaker 2.2.0 as its solved in that release.

**Comment by cassianoleal** [comment]
Confirmed. I had not noticed that 2.2.0 had been released already. Thanks!
