### ISSUE TITLE
having error finding my class using beaker

### ISSUE THREAD

**Issue by developerinlondon** [puppetlabs/beaker#728]
hi there,

i am using the example from the beaker-rspec and having problems finding my class. 

here is my error:
```
[/Users/nayeem.syed/Documents/bgch/puppet-installer:feature/add-resolv-conf:d62c707:+I+M+U]$ rspec spec/acceptance/bgch_bastion_rspec.rb 
Beaker::Hypervisor, found some vagrant boxes to create
==> ubuntu-server-1404-x64: Forcing shutdown of VM...
==> ubuntu-server-1404-x64: Destroying VM and associated drives...
Bringing machine 'ubuntu-server-1404-x64' up with 'virtualbox' provider...
==> ubuntu-server-1404-x64: Importing base box 'puppetlabs/ubuntu-14.04-64-nocm'...
==> ubuntu-server-1404-x64: Matching MAC address for NAT networking...
==> ubuntu-server-1404-x64: Checking if box 'puppetlabs/ubuntu-14.04-64-nocm' is up to date...
==> ubuntu-server-1404-x64: Setting the name of the VM: defaultyml_ubuntu-server-1404-x64_1425394474386_17455
==> ubuntu-server-1404-x64: Clearing any previously set network interfaces...
==> ubuntu-server-1404-x64: Preparing network interfaces based on configuration...
    ubuntu-server-1404-x64: Adapter 1: nat
    ubuntu-server-1404-x64: Adapter 2: hostonly
==> ubuntu-server-1404-x64: Forwarding ports...
    ubuntu-server-1404-x64: 22 => 2222 (adapter 1)
==> ubuntu-server-1404-x64: Running 'pre-boot' VM customizations...
==> ubuntu-server-1404-x64: Booting VM...
==> ubuntu-server-1404-x64: Waiting for machine to boot. This may take a few minutes...
    ubuntu-server-1404-x64: SSH address: 127.0.0.1:2222
    ubuntu-server-1404-x64: SSH username: vagrant
    ubuntu-server-1404-x64: SSH auth method: private key
    ubuntu-server-1404-x64: Warning: Connection timeout. Retrying...
==> ubuntu-server-1404-x64: Machine booted and ready!
==> ubuntu-server-1404-x64: Checking for guest additions in VM...
==> ubuntu-server-1404-x64: Setting hostname...
==> ubuntu-server-1404-x64: Configuring and enabling network interfaces...
==> ubuntu-server-1404-x64: Mounting shared folders...
    ubuntu-server-1404-x64: /vagrant => /Users/nayeem.syed/Documents/bgch/puppet-installer/.vagrant/beaker_vagrant_files/default.yml
Allocated a PTY on 10.255.44.172 for "sudo su -c \"cp -r .ssh /root/.\""
Allocated a PTY on 10.255.44.172 for "sudo su -c \"sed -ri 's/^#?PermitRootLogin no|^#?PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config\""
Allocated a PTY on 10.255.44.172 for "sudo su -c \"service ssh restart\""
localhost $ scp /Users/nayeem.syed/Documents/bgch/puppet-installer/modules/bgch_bastion ubuntu-server-1404-x64:/etc/puppetlabs/puppet/modules/bgch_bastion {:ignore => [".bundle", ".git", ".idea", ".vagrant", ".vendor", "vendor", "acceptance", "bundle", "spec", "tests", "log", ".", ".."]}

bgch_bastion class
  running puppet code
localhost $ scp /var/folders/cg/j_8tw58n60nc098k36yfvwvm000120/T/beaker20150303-25498-7dl2fx ubuntu-server-1404-x64:/tmp/apply_manifest.pp.kVqx1G {:ignore => }
    should work with no errors (FAILED - 1)
Destroying vagrant boxes
==> ubuntu-server-1404-x64: Forcing shutdown of VM...
==> ubuntu-server-1404-x64: Destroying VM and associated drives...

Failures:

  1) bgch_bastion class running puppet code should work with no errors
     On host ``
     Failure/Error: apply_manifest(pp, :catch_failures => true)
     Beaker::Host::CommandFailure: Host 'ubuntu-server-1404-x64' exited with 1 running:
 puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.kVqx1G
Last 10 lines of output were:
	Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
	   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
	Info: Loading facts
	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bgch_bastion at /tmp/apply_manifest.pp.kVqx1G:1 on node ubuntu-server-1404-x64
	Wrapped exception:
	Could not find declared class bgch_bastion
	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bgch_bastion at /tmp/apply_manifest.pp.kVqx1G:1 on node ubuntu-server-1404-x64
       
       Host 'ubuntu-server-1404-x64' exited with 1 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.kVqx1G
       Last 10 lines of output were:
       	Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
       	   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
       	Info: Loading facts
       	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bgch_bastion at /tmp/apply_manifest.pp.kVqx1G:1 on node ubuntu-server-1404-x64
       	Wrapped exception:
       	Could not find declared class bgch_bastion
       	Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class bgch_bastion at /tmp/apply_manifest.pp.kVqx1G:1 on node ubuntu-server-1404-x64
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/host.rb:290:in `exec'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/helpers.rb:88:in `block in on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/shared/host_manager.rb:95:in `run_block_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/helpers.rb:78:in `on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/helpers.rb:953:in `block in apply_manifest_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/shared/host_manager.rb:95:in `run_block_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/patterns.rb:32:in `block_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/helpers.rb:882:in `apply_manifest_on'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/beaker-2.5.0/lib/beaker/dsl/helpers.rb:960:in `apply_manifest'
     # ./spec/acceptance/bgch_bastion_rspec.rb:11:in `block (3 levels) in <top (required)>'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_exec'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/extensions/instance_eval_with_args.rb:16:in `instance_eval_with_args'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:116:in `block in run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:248:in `with_around_each_hooks'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example.rb:113:in `run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:515:in `block in run_examples'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `map'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:511:in `run_examples'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:496:in `run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `block in run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `map'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/example_group.rb:497:in `run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block (2 levels) in run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `map'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:24:in `block in run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/command_line.rb:21:in `run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:103:in `run'
     # /Users/nayeem.syed/gems/ruby/2.1.0/gems/rspec-core-2.99.2/lib/rspec/core/runner.rb:17:in `block in autorun'

Finished in 14.42 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/acceptance/bgch_bastion_rspec.rb:5 # bgch_bastion class running puppet code should work with no errors

```

here is my spec file:
```ruby
require 'spec_helper_acceptance'

describe 'bgch_bastion class' do
  describe 'running puppet code' do
    it 'should work with no errors' do
      pp = <<-EOS
        class { 'bgch_bastion': }
      EOS

      # Run it twice and test for idempotency
      apply_manifest(pp, :catch_failures => true)
      expect(apply_manifest(pp, :catch_failures => true).exit_code).to be_zero
    end

  end
end
```

and here is the spec_helper_acceptance.rb:
```ruby
require 'beaker-rspec'
require 'pry'

hosts.each do |host|
  # Install Puppet
  on host, install_puppet
  on hosts, "mkdir -p #{host['distmoduledir']}"
end

RSpec.configure do |c|
  module_root = File.expand_path(File.join(File.dirname(__FILE__), '..'))
  module_name = module_root.split('/').last

  c.formatter = :documentation

  # Configure all nodes in nodeset
  c.before :suite do
    # Install module
#    puppet_module_install(:source => module_root, :module_name => module_name)
    puppet_module_install(:source => "#{module_root}/modules/bgch_bastion", :module_name => 'bgch_bastion')
    
    hosts.each do |host|
      shell("/bin/touch #{default['puppetpath']}/hiera.yaml")
      on host, puppet('module','install','puppetlabs-stdlib'), { :acceptable_exit_codes => [0,1] }

 #     binding.pry
    end
  end
end
```

When i try enabling pry like mentioned on the doc I get the error below:
```
[1] pry(#<RSpec::Core::ExampleGroup>)> hosts
NoMethodError: undefined method `process_line' for #<SpecInfra::Command::Ubuntu:0x007faba537bee8>
from /Users/nayeem.syed/gems/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:404:in `process_command'
```

any ideas why i am having this problem... it seems quite straightforward on the doc but not quite working. 
I tried asking around on #puppet-dev irc with no luck either... :-(

**Comment by developerinlondon** [comment]
ok it appears i needed to add config-type to git on my default.yml file:
```yaml
HOSTS:
  ubuntu-server-1404-x64:
    roles:
      - master
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    hypervisor: vagrant
CONFIG:
  log_level: debug
  type: git

```
